### ISSUE TITLE
building from source

### ISSUE THREAD

**Issue by alexmyczko** [rewtnull/amigafonts#1]
is there some sources of some of the generated fonts? can they be included in here including the build scripts?

**Comment by rewtnull** [comment]
Sources? I can give you the original amiga fonts if that's what you're asking for. These multi platform fonts were hand crafted though and not generated in that sense.

//Marcus

On 9 April 2019 09:02:51 CEST, Alex Myczko <notifications@github.com> wrote:
>is there some sources of some of the generated fonts? can they be
>included in here including the build scripts?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rewtnull/amigafonts/issues/1

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by alexmyczko** [comment]
Would it be possible to drop the ' from the filenames? they are a bit cumbersome to escape in unix like shells for users, and some software seems to have problems with such filenames (linux setfont)
