### ISSUE TITLE
license

### ISSUE THREAD

**Issue by alexmyczko** [rewtnull/amigafonts#3]
would there be a chance to relicense the cc-whatever license to say ofl-1.1 or anything that is considered free by dfsg?

i am trying to get this into debian (main, not contrib/non-free) and got this rejected for:

unfortunately I have to reject the package, as the CC-BY-NC-SA-3.0 license is not DFSG compatible.

https://www.debian.org/social_contract

**Comment by rewtnull** [comment]
> would there be a chance to relicense the cc-whatever license to say ofl-1.1 or anything that is considered free by dfsg?
> 
> i am trying to get this into debian (main, not contrib/non-free) and got this rejected for:
> 
> unfortunately I have to reject the package, as the CC-BY-NC-SA-3.0 license is not DFSG compatible.
> 
> https://www.debian.org/social_contract

Hi there. Thanks for reaching out. Is GPL+FE not enough to cover dfsg? If that's a no-go, I will gladly look over the licensing.

**Comment by alexmyczko** [comment]
the point is it's licensed for one or the-other, and i state it like that. i can't just drop something that upstream (=you) says it's licensed like that, but sure drop the CC-stuff and it's fine :)

**Comment by rewtnull** [comment]
I understand, well let's drop the CC then and get it over with! :)
