### ISSUE TITLE
question from debian ftp master

### ISSUE THREAD

**Issue by alexmyczko** [rewtnull/amigafonts#5]
thank your for clarification:

Hello,

I notice that upstream has relicensed from CC-BY-NC-SA-3.0 to GPL with
the fonts exception, after a previous REJECT from NEW.

The upstream maintainer does not, however, hold copyright on all of
the fonts -- they are from a number of different authors.  So I am not
sure he has the right to relicense the whole package.

Could you ask upstream whether this relicensing was unilateral,
please?

**Comment by alexmyczko** [comment]
<tarzeau> can i get an answer to
https://github.com/rewtnull/amigafonts/issues/5 please?
<@truck> "These fonts are replications, not conversions, of the original
fonts.  As such, they are derivative works. I can relicense them, as
they are mine. There is no upstream."
<@dMG> thank you truck for clearing it up, that is basically in line
with what i was thinking to answer too :)

You don't get a relicense something unilaterally just because it is a
derivative work!  Also, "they are derivative works" and "there is no
upstream" would seem to be in tension with each other.

I think we need more detail on what is meant by "replications

**Comment by alexmyczko** [comment]
13:57 <SOMEONE> tarzeau: the change was just made by one author after complaints that the license is not DFSG compatible; the reasoning for that change was 
            rather strange and from my point of view wrong; I would have expected a note from the other authors (or maybe an irc log) where they agree to 
            the license change and probably added as comment to your debian/copyright

that would resolve all issues! please?

**Comment by fcambus** [comment]
There seems to be a lot of confusion here, and I think it all comes from the "14. LEGAL STUFF" section in README.

This package contains faithfully remade Amiga fonts. As far as I know, the fonts included in this repository were created using a vector font editor, by redrawing all characters by hand.

If we take the P0T-NOoDLE font, we can see this in README:

P0T-NOoDLE is © Leo "Nudel" Davidson
ttf, fon, eot, raw & psf v1/v2 versions are © dMG/t!s^dS!

The original P0T-NOoDLE Amiga font (which is not included in this repository!) was created by Leo Davidson, a.k.a "Nudel". This line about the original Amiga version author is given for information purpose.
The TTF file included in this repository was created by dMG, and so do all other exported formats.

This is the same for all other fonts contained in this repository, those are all hand-drawn by dMG. Therefore, all fonts contained in this repository were all created by dMG, who is the single author and claims the copyright on those recreations.
